version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}-nginx
    ports:
      - '80:80'
      - '8000:443'
    volumes:
      - ./docker/nginx.conf:/tmp/default.template
      - ./docker/certs:/etc/certs
      - ./:/var/www/html
    depends_on:
      - wordpress
    restart: always
    entrypoint: /bin/bash -c 'cat /tmp/default.template | sed "s/\\\$$domain/localhost/g" > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'
  wordpress:
    build:
      context: .
      dockerfile: DockerFile
    container_name: ${APP_NAME}-wordpress
    volumes:
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./:/var/www/html
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql:5.7.26
    container_name: ${APP_NAME}-mysql
    volumes:
       - db_data:/var/lib/mysql
       # - ./docker/initdb/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    restart: always
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    volumes:
      - ./config/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '8080:80'
    links:
      - mysql:mysql
  mailhog:
   image: mailhog/mailhog
   ports:
     - "8025:8025"
     - "1025:1025"
  composer:
    image: composer
    container_name: ${DB_HOST}-composer
    working_dir: /var/www/html
    restart: 'no'
    volumes:
      - ./:/var/www/html:rw,cached
       
volumes:
    db_data: {}